on: push
jobs:
  testing-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/hello
        id: hello
        with:
          who-to-greet: "All!"
      - run: |
          echo "Time ${{ steps.hello.outputs.time }}"  
      - uses: ./.github/actions/issue
        id: issue
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Title
          body: Body
          assignees: 'jank6r'
      - run: |
          echo "Time ${{ steps.id.outputs.issue }}"  
      

      